# Generated by Django 3.0.5 on 2020-04-30 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 2, 0, 2, 324799), verbose_name='date published'),
        ),
    ]
